import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

import Header from "./components/header";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // suppress hydration warnings
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* global header*/}
        <Header />

        <div className="pb-5"></div>

        {/* page content */}
        {children}

        {/* load i18n after page hydrated */}
        <Script src="/js/i18n.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
